<?xml version="1.0"?>
<package format="3">
    <name>rviz_nmpc_plugin</name>
    <version>2.0.0</version>
    <description>RViz2 panel for SDF-NMPC controller.</description>

    <maintainer email="martin.jacquet@ntnu.no">mjacquet</maintainer>
    <author email="martin.jacquet@ntnu.no">mjacquet</author>
    <license>BSD-3-Clause</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>rclcpp</depend>
    <depend>std_srvs</depend>
    <depend>pluginlib</depend>
    <depend>rviz_common</depend>

    <build_depend>qtbase5-dev</build_depend>
    <exec_depend>libqt5-core</exec_depend>
    <exec_depend>libqt5-widgets</exec_depend>

    <export>
        <rviz plugin="${prefix}/plugin_description.xml"/>
        <build_type>ament_cmake</build_type>
    </export>
</package>